### ISSUE TITLE
Landing Page development

### ISSUE THREAD

**Issue by Zimzams** [holistic-web/stock-tracker#1]
Basic home screen. Room for creativity on basic design.

- [x] dev set up a clear, black and white / muted paper style colour scheme for the site
- [x] all existing pages should be using clear "full screen" designs
- [x] each thing to look at fills the screen and avoids clutter / distractions

inspiration from this [website's landing page ](http://www.deluxcoin.com/) 

Things that i like about it: static banner, vertical scrolling design, ticker(pauses on hover) + crypto vs stock stats on front page.

Changes to consider would be using a more minimal, orange-> black theme, decreasing stats overload slightly, and include a few more segments describing basic functionality/user flow. Link to example profiles to demonstrate that part of the website. Also moderately prefer right-hand orientation with menus.

... so TL:DR mixing the deluxcoin home page with the style of private mockup design

**Comment by michaelfitzhavey** [comment]
# Todo:

### General
- [ ] create holding page for the site that loads while the rest of the functionality is in development
- [ ] orange black colour scheme

### Header
- [ ] style similar to design
- [ ]  disable not yet implemented sections
- [ ] add coming soon somewhere

### Landing Image
- [ ] fullscreen
- [ ] with text
- [ ] choose quality image (unplash)
- [ ] opens up register modal

### Register Modal
- [ ] add welcome text
- [ ] take email
- [ ] store email in database]
- [ ] thank you message
- [ ] gdpr compliant

### Demo of Chart JS
- [ ] one type of chart loaded and styled
- [ ] another type (there should be a demo of at least two types)
- [ ] make data seem relevant to the stock market
- [ ] load data live from an api

**Comment by michaelfitzhavey** [comment]
closed as tasks have been migrated to seperate issues
